// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pangeanembassy.security.domain;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import pangeanembassy.security.domain.RoleDataOnDemand;

privileged aspect RoleIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RoleIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RoleIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: RoleIntegrationTest: @Transactional;
    
    @Autowired
    private RoleDataOnDemand RoleIntegrationTest.dod;
    
    @Test
    public void RoleIntegrationTest.testCountRoles() {
        org.junit.Assert.assertNotNull("Data on demand for 'Role' failed to initialize correctly", dod.getRandomRole());
        long count = pangeanembassy.security.domain.Role.countRoles();
        org.junit.Assert.assertTrue("Counter for 'Role' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RoleIntegrationTest.testFindRole() {
        pangeanembassy.security.domain.Role obj = dod.getRandomRole();
        org.junit.Assert.assertNotNull("Data on demand for 'Role' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Role' failed to provide an identifier", id);
        obj = pangeanembassy.security.domain.Role.findRole(id);
        org.junit.Assert.assertNotNull("Find method for 'Role' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Role' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RoleIntegrationTest.testFindAllRoles() {
        org.junit.Assert.assertNotNull("Data on demand for 'Role' failed to initialize correctly", dod.getRandomRole());
        long count = pangeanembassy.security.domain.Role.countRoles();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Role', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<pangeanembassy.security.domain.Role> result = pangeanembassy.security.domain.Role.findAllRoles();
        org.junit.Assert.assertNotNull("Find all method for 'Role' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Role' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RoleIntegrationTest.testFindRoleEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Role' failed to initialize correctly", dod.getRandomRole());
        long count = pangeanembassy.security.domain.Role.countRoles();
        if (count > 20) count = 20;
        java.util.List<pangeanembassy.security.domain.Role> result = pangeanembassy.security.domain.Role.findRoleEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Role' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Role' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RoleIntegrationTest.testFlush() {
        pangeanembassy.security.domain.Role obj = dod.getRandomRole();
        org.junit.Assert.assertNotNull("Data on demand for 'Role' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Role' failed to provide an identifier", id);
        obj = pangeanembassy.security.domain.Role.findRole(id);
        org.junit.Assert.assertNotNull("Find method for 'Role' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRole(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Role' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RoleIntegrationTest.testMerge() {
        pangeanembassy.security.domain.Role obj = dod.getRandomRole();
        org.junit.Assert.assertNotNull("Data on demand for 'Role' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Role' failed to provide an identifier", id);
        obj = pangeanembassy.security.domain.Role.findRole(id);
        boolean modified =  dod.modifyRole(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        pangeanembassy.security.domain.Role merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Role' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RoleIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Role' failed to initialize correctly", dod.getRandomRole());
        pangeanembassy.security.domain.Role obj = dod.getNewTransientRole(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Role' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Role' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Role' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RoleIntegrationTest.testRemove() {
        pangeanembassy.security.domain.Role obj = dod.getRandomRole();
        org.junit.Assert.assertNotNull("Data on demand for 'Role' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Role' failed to provide an identifier", id);
        obj = pangeanembassy.security.domain.Role.findRole(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Role' with identifier '" + id + "'", pangeanembassy.security.domain.Role.findRole(id));
    }
    
}
